name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: go mod download github.com/MakeNowJust/heredoc
      - uses: actions/checkout@v2
      - uses: cli/gh-extension-precompile@v1.2.1


